[workspace]

[package]
name = "control-server-ota"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "control-server-ota"
test = false
bench = false

[dependencies]
control-server = { path = "../control-server" }
embassy-executor = { version = "0.10", features = ["platform-cortex-m", "executor-thread"] }
embassy-time = { version = "0.5", features = ["generic-queue-64"] }
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = "1.0"
