[package]
name = "gd32f470"
version = "0.1.0"
edition = "2021"
description = "svd2rust-generated PAC for GD32F470 (from GigaDevice DFP 3.5.0 SVD)"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m = "0.7"
vcell = "0.1"
critical-section = "1"

[features]
default = ["critical-section"]
critical-section = []
rt = ["cortex-m-rt/device"]

[dependencies.cortex-m-rt]
optional = true
version = "0.7"
